[package]
name = "embedded-savegame"
version = "0.1.0"
edition = "2024"

[dependencies]
crc32fast = { version = "1.5.0", default-features = false }
eeprom24x = { version = "0.7.2", optional = true }

[features]
eeprom24x = ["dep:eeprom24x"]
